config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root "home#index"
  get '/home', to: 'home#index'
  resources :recipe_foods, only: %i[new create destroy]
  resources :general_shopping_lists, only: [:index]
  resources :users, only: %i[index show new create destroy]
  resources :recipes, only: %i[index show new create destroy]
  get '/public_recipe', to: 'recipes#public_recipe', as: 'public_recipe'
  resources :foods, only: %i[index show new create destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :description, presence: true
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :preparation_time, presence: true, numericality: { greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than: 0 }

  scope :by_user, ->(user_id) { where(user_id:) }
  scope :by_food, ->(food_id) { joins(:foods).where(foods: { id: food_id }) }
  scope :public_recipes, -> { where(public: true) }
  scope :private_recipes, -> { where(public: false) }

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:public_recipe]

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: params[:id])

    if @recipe_foods.any?
      @ingredients = []
      @recipe_foods.each do |recipe_food|
        @ingredients << {
          id: recipe_food.id,
          name: Food.find_by(id: recipe_food.food_id).name,
          quantity: recipe_food.quantity,
          measurement_unit: Food.find_by(id: recipe_food.food_id).measurement_unit,
          price: recipe_food.quantity * Food.find_by(id: recipe_food.food_id).price
        }
      end
    end

    return unless @recipe.nil?

    flash[:error] = 'Recipe not found'
    redirect_to recipes_path
  end

  def new
    @recipe = Recipe.new
  end

  def index
    @recipes = current_user.recipes.order(created_at: :desc)
  end

  def public_recipe
    @recipes = Recipe.where(public: true).order(created_at: :desc).includes([:user])
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe was successfully created.'
      redirect_to recipes_path
    else
      flash[:alert] = 'Something went wrong! Recipe was not created.'
      render 'new'
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    RecipeFood.where(recipe_id: @recipe.id).destroy_all

    if @recipe.destroy
      flash[:notice] = 'Recipe was successfully deleted.'
      redirect_to recipes_path
    else
      flash.now[:alert] = 'Something went wrong! Recipe was not deleted.'
      render 'show'
    end
  end
end

app/views/recipes/index.html.erb
<div class="body-max-width mx-auto mt-5">
  <div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center">
        <i class="bi bi-journal me-2 fs-4"></i>
        <h4 class="m-0">Your Recipes</h4>
      </div>
      <%= link_to '+ Add New Recipe', new_recipe_path, class: 'btn btn-secondary' %>
    </div>
    <div class="w-75 mx-auto my-3 d-flex flex-column gap-3">
      <% if @recipes.any? %>
        <% @recipes.each do |recipe| %>
          <div class="card flex-row gap-2 recipe-card">
            <div class="col-3 bg-light border-end rounded-start p-3">
              <h5><%= link_to recipe.name, recipe, class: 'card-title text-decoration-none' %></h5>
              <%= button_to 'Delete', recipe, method: :delete, class: 'btn btn-outline-primary px-4 py-1' %>
            </div>
            <div clas="col-7">
              <p class="card-text p-3"><%= recipe.description %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="m-0 text-center">You haven't created any recipes yet.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="card d-flex w-25 p-3 mx-auto mt-5">
  <h2 class="text-center">New Recipe</h2>
  <%= form_for @recipe, html: { class: 'd-flex flex-column' } do |f| %>
    <div class="form-group d-flex flex-column gap-2">
      <%= f.label :name, class: 'text-primary' %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group d-flex flex-column gap-2">
      <%= f.label :preparation_time, class: 'text-primary' %>
      <%= f.number_field :preparation_time, class: 'form-control', required: true %>
    </div>

    <div class="form-group d-flex flex-column gap-2">
      <%= f.label :cooking_time, class: 'text-primary' %>
      <%= f.number_field :cooking_time, class: 'form-control', required: true %>
    </div>

    <div class="form-group d-flex flex-column gap-2">
      <%= f.label :description, class: 'text-primary' %>
      <%= f.text_area :description, class: 'form-control', required: true, rows: 4 %>
    </div>

    <div class="form-check">
      <%= f.label :public, class: 'form-check-label' do %>
        <%= f.check_box :public, class: 'form-check-input' %>
        Public Recipe
      <% end %>
    </div>

    <div class="form-group d-flex">
      <%= f.submit 'Add New Recipe', class: 'btn btn-primary mt-2 w-100 px-4 mb-2' %>
    </div>
  <% end %>

  <%= link_to 'Back to Recipes', recipes_path, class: 'btn btn-outline-primary btn-block border-0' %>
</div>

app/views/recipes/public_recipe.html.erb
<div class="body-max-width mx-auto mt-5">
  <div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center">
        <i class="bi bi-book me-2 fs-4"></i>
        <h4 class="m-0">Public Recipes</h4>
      </div>
      <%= link_to '+ Add New Recipe', new_recipe_path, class: 'btn btn' %>
    </div>
    <div class="w-75 mx-auto my-3 d-flex flex-column gap-3">
      <% if @recipes.any? %>
        <% @recipes.each do |recipe| %>
          <div class="card flex-row gap-2 recipe-card">
            <div class="col-3 bg-light border-end rounded-start p-3">
              <h5><%= link_to recipe.name, recipe, class: 'card-title text-decoration-none' %></h5>
              <% if current_user == recipe.user %>
                <%= button_to 'Delete', recipe, method: :delete, class: 'btn btn-outline px-4 py-1' %>
              <% end %>
            </div>
            <div clas="col-7">
              <p class="card-text p-3"><%= recipe.description %></p>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="m-0 text-center">You haven't created any recipes yet.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="body-max-width mx-auto mt-5">
  <div class="card w-50 mx-auto">
    <div class="card-header d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center">
        <i class="bi bi-journal me-2 fs-4"></i>
        <h4 class="m-0"><%= @recipe.name %></h4>
      </div>
      <%= link_to 'Back to Recipes', recipes_path, class: 'btn btn-outline-primary' %>
    </div>
    <div class="d-flex flex-column gap-1 p-3">
      <div class="d-flex justify-content-between">
        <p><strong>Preparation Time:</strong> <%= @recipe.preparation_time %> minutes</p>
        <div class="form-check form-switch">
          <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
          <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" <%= @recipe.public ? 'checked' : '' %> disabled>
        </div>
      </div>
      <p><strong>Cooking Time:</strong> <%= @recipe.cooking_time %> minutes</p>
      <p><strong>Description:</strong> <%= @recipe.description %></p>
      <div class="d-flex justify-content-between">
        <%= link_to general_shopping_lists_path, class: 'btn btn-primary px-5' do %>
          Go to my Shopping List
          <i class="bi bi-box-arrow-up-right text-white ms-1"></i>
        <% end %>
        <% if current_user == @recipe.user %>
          <%= link_to '+ Add Ingredient', new_recipe_food_path(recipe_id: @recipe.id), class: 'btn btn-primary px-5' %>
        <% else %>
          <%= button_to '+ Add Ingredient', new_recipe_food_path(recipe_id: @recipe.id), class: 'btn btn-primary px-5 disabled' %>
        <% end %>
      </div>
      <% if @ingredients.present? %>
        <div class="h-75 border-bottom my-4"></div>
        <div class="table-responsive">
          <table class="table table-hover mb-0 border">
            <thead>
              <tr>
                <th class="bg-pink text-white fw-normal ps-3">Ingredient</th>
                <th class="bg-pink text-white fw-normal text-center">Quantity</th>
                <th class="bg-pink text-white fw-normal">Price</th>
                <th class="bg-pink text-white fw-normal pe-3 text-center">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @ingredients.each do |item| %>
                <tr>
                  <td class="ps-3"><%= item[:name] %></td>
                  <td class="text-center">
                    <%= item[:quantity] %>
                    <%= item[:measurement_unit] %><% if item[:measurement_unit].length > 2 && item[:quantity] > 1 %>s
                    <% end %>
                  </td>
                  <td><%= number_to_currency(item[:price]) %></td>
                  <td class="pe-3 text-center col-2">
                    <% if current_user == @recipe.user %>
                      <%= button_to 'Remove', recipe_food_path(item[:id]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-primary py-0 px-2 border-0' %>
                    <% else %>
                      <small class="fst-italic text-primary">Not allowed</small>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>