config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root "home#index"
  get '/home', to: 'home#index'
  resources :recipe_foods, only: %i[new create destroy]
  resources :general_shopping_lists, only: [:index]
  resources :users, only: %i[index show new create destroy]
  resources :recipes, only: %i[index show new create destroy]
  get '/public_recipe', to: 'recipes#public_recipe', as: 'public_recipe'
  resources :foods, only: %i[index show new create destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @lastest_public_recipes = Recipe.where(public: true).order(created_at: :desc).limit(3)
    @user_lastest_recipes = current_user.recipes.order(created_at: :desc).limit(3)
    @user_lastest_foods = current_user.foods.order(created_at: :desc).limit(5)
  end
end

app/views/home/index.html.erb
<div class="d-flex justify-content-center py-5 body-max-width m-auto gap-5">
  <div class="d-flex flex-column gap-5 w-100">
    <div>
      <div class="card">
        <div class="card-header d-flex flex-row justify-content-between">
          <div class="d-flex align-items-center">
            <i class="bi bi-book me-2 fs-4"></i>
            <h5 class="m-0">Latest Public Recipes</h5>
          </div>
          <small class="d-none gap-2">
            <%= link_to "View all", public_recipe_path, class:"text-decoration-none text-primary align-self-center" %>
            <i class="bi bi-box-arrow-up-right text-secondary align-self-center"></i>
          </small>
        </div>
        <div class="list-group list-group-flush">
          <% if @lastest_public_recipes != [] %>
            <% @lastest_public_recipes.each do |recipe| %>
              <button class="d-flex gap-3 list-group-item list-group-item-action button-list" 
                            onclick="window.location.href='<%= recipe_path(recipe) %>'" 
                            onmouseover="changeIconClass(this, 'bi-star', 'bi-star-fill')"
                            onmouseout="changeIconClass(this, 'bi-star-fill', 'bi-star')">
                <i class="bi bi-star align-self-center fs-5"></i>
                <div class="d-flex flex-column">
                  <h6 class="m-0"><%= recipe.name %></h6>
                  <small class="text-secondary"><i class="bi bi-clock-history"></i> <%= time_ago_in_words(recipe.created_at) %> ago</small>
                </div>
              </button>
            <% end %>
          <% else %>
            <p class="text-center my-2">There are no public recipes yet.</p>
          <% end %>
        </div>
      </div>
      <%= link_to "+ Add New Recipe", new_recipe_path, class:"btn btn-secondary float-end mt-2" %>
    </div>
    <div>
      <div class="card">
        <div class="card-header d-flex flex-row justify-content-between">
          <div class="d-flex align-items-center">
            <i class="bi bi-journal me-2 fs-4"></i>
            <h5 class="m-0">Your Latest Recipes</h5>
          </div>
          <small class="d-none gap-2">
            <%= link_to "View all", recipes_path, class:"text-decoration-none text-primary align-self-center" %>
            <i class="bi bi-box-arrow-up-right text-primary align-self-center"></i>
          </small>
        </div>
        <div class="list-group list-group-flush">
          <% if @user_lastest_recipes != [] %>
            <% @user_lastest_recipes.each do |recipe| %>
              <button class="d-flex gap-3 list-group-item list-group-item-action button-list" 
              onclick="window.location.href='<%= recipe_path(recipe) %>'" 
              onmouseover="changeIconClass(this, 'bi-star', 'bi-star-fill')"
              onmouseout="changeIconClass(this, 'bi-star-fill', 'bi-star')">
                <i class="bi bi-star align-self-center fs-5"></i>
                <div class="d-flex flex-column">
                  <h6 class="m-0"><%= recipe.name %></h6>
                  <small class="text-secondary"><i class="bi bi-clock-history"></i> <%= time_ago_in_words(recipe.created_at) %> ago</small>
                </div>
              </button>
            <% end %>
          <% else %>
            <p class="text-center my-2">You haven not added any recipe yet.</p>
          <% end %>
        </div>
      </div>
      <%= link_to "+ Add New Recipe", new_recipe_path, class:"btn btn-secondaryfloat-end mt-2" %>
    </div>
  </div>
  <div class="w-50 d-flex flex-column">
    <%= link_to(general_shopping_lists_path, class: "btn btn-secondary w-100 fs-5 mb-4") do %>
      Go to Shopping List
      <i class="bi bi-box-arrow-up-right text-white ms-3"></i>
    <% end %>
    <div class="card w-100">
      <div class="card-header d-flex flex-row justify-content-between">
        <div class="d-flex align-items-center">
          <i class="bi bi-cookie me-2 fs-4"></i>
          <h5 class="m-0">New to Food Inventory</h5>
        </div>
        <small class="d-none gap-2">
          <%= link_to "View all", foods_path, class:"text-decoration-none text-primary align-self-center" %>
          <i class="bi bi-box-arrow-up-right text-primary align-self-center"></i>
        </small>
      </div>
      <div class="list-group list-group-flush">
        <% if @user_lastest_foods != [] %>
          <% @user_lastest_foods.each do |food| %>
            <button class="d-flex gap-3 list-group-item list-group-item-action button-list" 
                            onclick="window.location.href='<%= root_path %>'" 
                            onmouseover="changeIconClass(this, 'bi-star', 'bi-star-fill')"
                            onmouseout="changeIconClass(this, 'bi-star-fill', 'bi-star')">
              <i class="bi bi-star lh-1 fs-5"></i>
              <div class="d-flex flex-column">
                <p class="m-0"><%= food.name %></p>
                <small class="text-primary ms-3">
                  Spence: <%= food.quantity %> <%= food.measurement_unit %> • Price: $<%= food.price %> per <%= food.measurement_unit %>.
                </small>
              </div>
            </button>
          <% end %>
        <% else %>
          <p class="text-center my-2">You have not added any food yet.</p>
        <% end %>
      </div>
    </div>
    <%= link_to "+ Add New Food", new_food_path, class: "btn btn-secondary mt-2 ms-auto" %>
  </div>
</div>