config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root "home#index"
  get '/home', to: 'home#index'
  resources :recipe_foods, only: %i[new create destroy]
  resources :general_shopping_lists, only: [:index]
  resources :users, only: %i[index show new create destroy]
  resources :recipes, only: %i[index show new create destroy]
  get '/public_recipe', to: 'recipes#public_recipe', as: 'public_recipe'
  resources :foods, only: %i[index show new create destroy]
end

app/views/layouts/_navbar.html.erb
<div class="bg-light d-flex justify-content-center px-5 border-bottom">
  <nav class="navbar navbar-expand-lg navbar-light d-flex w-100 body-max-width">
    <%= image_tag('logo.png', alt: 'Recipe App Logo', size: '50x50', class: 'me-3') %>
    <ul class="navbar-nav gap-4 flex-row justify-self-start">
      <li class="nav-item active">
        <%= link_to "Home", home_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Public Recipes", public_recipe_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Recipes", recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Food", foods_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Shopping List", general_shopping_lists_path, class: "nav-link" %>
      </li>
    </ul>
    <div class="justify-self-end ms-auto d-flex align-items-center gap-2">
      <% if user_signed_in? %>
        <li class="nav-item dropdown list-unstyled">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="w-100 py-1">
              <%= link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class:"w-100 mx-3 text-secondary" do %>
                <i class="bi bi-box-arrow-right"></i> Log out
              <% end %>
            </li>
          </ul>
        </li>
        <%= image_tag("https://i.pravatar.cc/50?img=0", alt: 'Recipe App Logo', size: '50x50', class: 'rounded-circle bg-white border p-1') %>
      <% end %>
    </div>
  </nav>
</div>
<div class="w-100 d-flex justify-content-center">
  <% if notice %>
    <p class="notice mt-2 py-1 px-2 rounded"><%= notice %></p>
    <script>
      document.addEventListener("turbo:load", () => {
        fadeInOut('.notice');
      });
    </script>
  <% end %>
  <% if alert %>
    <p class="notice mt-2 py-1 px-2 rounded"><%= alert %></p>
    <script>
      document.addEventListener("turbo:load", () => {
        fadeInOut('.notice');
      });
    </script>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="px-5">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
      function changeIconClass(button, className, newClass) {
        let icon = button.querySelector('i.' + className);
        icon.classList.replace(className, newClass);
      }

      function fadeInOut(className) {
          let activeElement = document.querySelector(className);

          activeElement.classList.add('fade-in');
          setTimeout(() => {
            activeElement.classList.remove('fade-in');
            setTimeout(() => activeElement.remove(), 1000);
          }, 3000);
        };
    </script>
  </body>
</html>